### ISSUE TITLE
Create type (UserModel | undefined) to allow force unwrapping

### ISSUE THREAD

**Issue by mateow99** [cuappdev/resell-backend#41]
Since we know that we are expecting a user given they're logged in already due to our use of the CurrentUser decorator, we should force unwrap `userWithSaved`. Take a look at https://spin.atomicobject.com/2022/03/28/optional-undefined-typescript/ to see how optionals work and consider doing a refactor in the future converting all `SomeType | undefined` instances to `SomeType?`

_Originally posted by @chalo2000 in https://github.com/cuappdev/resell-backend/pull/38#discussion_r997436368_

**Comment by snajima** [comment]
This should be addressed when we address #55
