### ISSUE TITLE
Change similarity metric

### ISSUE THREAD

**Issue by snajima** [cuappdev/resell-backend#57]
If you take a look at the example provided here https://npm.io/package/string-similarity, similar strings would be 'sealed' and 'healed'. I don't think this is the kind of similarity that @JessieWang0706 had in mind. I think a conversation about what makes 2 items similar is needed and it seems like https://www.tensorflow.org/hub/tutorials/semantic_similarity_with_tf_hub_universal_encoder would do a better job at calculating this similarity. For now I am approving so that we can get some kind of similarity metric in since all we need to do in a future PR is replace the string similarity calculating with this encoder's calculation.

_Originally by @chalo2000 in #53_

**Comment by akmatchev** [comment]
Is the issue closed now that similar item algo is out?

**Comment by chalo2000** [comment]
yes this is the similarity metric I wanted. i am satisfied
